title: Download Portal
markdown: kramdown

# for atom feed
author:
  name: Loyd Osborne
  email: loyd.osborne@scyted.tv

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

- name: Git Auto Commit
  uses: stefanzweifel/git-auto-commit-action@v4.16.0